const phrases = [
  "Hoy vuelve a elegir intentarlo.",
  "La disciplina también se entrena.",
  "Haz algo hoy que tu yo de mañana agradezca.",
  "No subestimes el poder de repetir.",
  "Tu progreso está en los detalles.",
  "Avanzar lento sigue siendo avanzar.",
  "Medio centenar de días. Eso es constancia.",
  "La práctica de hoy mejora el mañana.",
  "Lo importante es seguir presente.",
  "Tu enfoque vale más que tu velocidad.",
  "Los hábitos nacen en días normales.",
  "Hoy suma aunque sea un poco.",
  "Lo constante supera a lo intenso.",
  "Estás aprendiendo a persistir.",
  "El esfuerzo silencioso también cuenta.",
  "La mejora diaria es acumulativa.",
  "Dos meses de compromiso.",
  "Sigue apareciendo.",
  "La repetición construye habilidad.",
  "Cada intento te entrena.",
  "Tu constancia tiene impacto.",
  "Mantén la dirección.",
  "Incluso los expertos empezaron así.",
  "Hoy es otra oportunidad.",
  "La perseverancia cambia resultados.",
  "Continúa aunque sea poco.",
  "La disciplina ya está creciendo.",
  "No pares ahora.",
  "La práctica moldea el carácter.",
  "Lo que repites se fortalece.",
  "El hábito ya está tomando forma.",
  "Tres cuartos de cien días.",
  "Mantén el enfoque.",
  "El progreso es acumulativo.",
  "La paciencia también es parte del proceso.",
  "Cada día cuenta.",
  "Hoy sigue construyendo.",
  "Tu consistencia habla por ti.",
  "La disciplina es una elección diaria.",
  "Repite lo que funciona.",
  "Pequeños pasos sostienen grandes metas.",
  "El compromiso se demuestra así.",
  "Hoy también vale la pena.",
  "Sigue aprendiendo del proceso.",
  "No necesitas prisa.",
  "Solo necesitas continuar.",
  "Noventa días de constancia.",
  "Estás desarrollando resistencia.",
  "El esfuerzo forma habilidades.",
  "Mantén tu propósito presente.",
  "Cada repetición fortalece tu mente.",
  "No abandones el proceso.",
  "La constancia crea resultados reales.",
  "Tu compromiso se vuelve identidad.",
  "Hoy sigue entrenando tu disciplina.",
  "Un día más de progreso.",
  "Cien días de constancia.",
  "Empieza el siguiente tramo.",
  "La perseverancia se nota.",
  "Tu esfuerzo ya tiene historia.",
  "Hoy repite el hábito.",
  "Continúa con intención.",
  "Mantén el rumbo.",
  "No pierdas el ritmo.",
  "Tu compromiso sigue firme.",
  "Cada día suma experiencia.",
  "La mejora continúa.",
  "Constancia en acción.",
  "Sigue fortaleciendo tu hábito.",
  "Lo que construyes importa.",
  "Avanza con calma.",
  "Confía en tu disciplina.",
  "Un día más de práctica.",
  "Estás formando carácter.",
  "Mantén la determinación.",
  "La persistencia funciona.",
  "Cuatro meses de constancia.",
  "Continúa el proceso.",
  "Haz lo que ya sabes hacer.",
  "La consistencia es poder.",
  "Hoy suma de nuevo.",
  "El hábito ya vive contigo.",
  "Perseverar también es crecer.",
  "Tu esfuerzo vale.",
  "Mantente presente.",
  "Sigue practicando.",
  "La disciplina se fortalece.",
  "Hoy repite el compromiso.",
  "Un paso más.",
  "Mantén tu enfoque.",
  "El progreso sigue.",
  "Tu constancia inspira.",
  "No sueltes el hábito.",
  "Perseverar cambia resultados.",
  "Estás entrenando tu mente.",
  "Hoy también cuenta.",
  "Continúa firme.",
  "El proceso te está formando.",
  "Sigue practicando tu disciplina.",
  "El progreso se acumula.",
  "Cada día refuerza tu hábito.",
  "Tu consistencia se nota.",
  "Hoy continúa el trabajo.",
  "Tu esfuerzo tiene dirección.",
  "La práctica te mejora.",
  "No pierdas la continuidad.",
  "Ciento cincuenta días.",
  "Mantén la intención clara.",
  "Sigue el ritmo que ya construiste.",
  "El hábito es parte de tu rutina.",
  "El progreso es silencioso.",
  "Continúa con determinación.",
  "Tu disciplina te acompaña.",
  "Hoy suma otra repetición.",
  "La perseverancia da frutos.",
  "Mantente constante.",
  "La práctica te fortalece.",
  "Tu constancia sigue viva.",
  "Seis meses de disciplina.",
  "El hábito ya es natural.",
  "Doscientos días de esfuerzo.",
  "Tu perseverancia se mantiene.",
  "La disciplina ya es parte de ti.",
  "El progreso sigue acumulándose.",
  "Ocho meses de compromiso.",
  "Un cuarto de mil días.",
  "Tu esfuerzo continúa firme.",
  "Mantén tu propósito claro.",
  "La constancia sigue marcando diferencia.",
  "Perseverar ya es normal para ti.",
  "Trescientos días de disciplina.",
  "Tu hábito es sólido.",
  "Continúa creciendo.",
  "Tu compromiso se mantiene.",
  "Cada día refuerza tu carácter.",
  "Trescientos cincuenta días.",
  "Casi un año completo.",
  "Un año de constancia.",
  "Sigues demostrando disciplina.",
  "La perseverancia continúa.",
  "Tu esfuerzo no se detiene.",
  "Cuatrocientos días de compromiso.",
  "La disciplina ya es parte de tu identidad.",
  "Tu perseverancia sigue firme.",
  "El hábito permanece.",
  "Tu constancia continúa creciendo.",
  "Cuatrocientos cincuenta días.",
  "Tu disciplina es real.",
  "El esfuerzo sigue sumando.",
  "La constancia te define.",
  "Cada día refuerza tu camino.",
  "Quinientos días de constancia.",
  "Gracias por empezar. Ese paso ya cuenta.",
  "Hazlo a tu ritmo, pero hazlo.",
  "No tiene que ser perfecto, solo constante.",
  "Un pequeño esfuerzo hoy vale mucho mañana.",
  "Estás construyendo algo importante.",
  "Si hoy cuesta, haz lo que puedas.",
  "Una semana completa. Bien hecho.",
  "Sigue, incluso si avanzas despacio.",
  "Confía en tu proceso.",
  "Ya llevas la mitad, no es poco.",
  "Si tropiezas, puedes volver a empezar.",
  "Cada día suma, aunque no lo notes.",
  "Tu esfuerzo tiene valor.",
  "Dos semanas. Eso habla de ti.",
  "Estás demostrando compromiso.",
  "Hoy también puedes lograrlo.",
  "Lo difícil también te enseña.",
  "Estás siendo más fuerte de lo que crees.",
  "Ya casi terminas este ciclo.",
  "Mañana celebras tu constancia.",
  "Comienza una nueva etapa.",
  "Puedes dar un pequeño paso extra.",
  "Hoy intenta hacerlo un poco mejor.",
  "Confía en ti.",
  "Estás formando un hábito real.",
  "Tu disciplina está creciendo.",
  "Incluso en días difíciles, aquí sigues.",
  "Cada repetición te fortalece.",
  "Mira cuánto has avanzado.",
  "Lo que haces hoy construye tu mañana.",
  "No necesitas motivación, ya tienes compromiso.",
  "Puedes con esto.",
  "Estás desarrollando carácter.",
  "La constancia se nota.",
  "Hazlo con intención.",
  "Tu esfuerzo tiene sentido.",
  "Estás más cerca de tu meta.",
  "Valora tu progreso.",
  "Esto ya es parte de ti.",
  "Eres más constante que antes.",
  "Sigue, estás haciendo algo grande.",
  "¿Listo para el siguiente reto?",
  "Lo hiciste. Y eso importa.",

  "Empieza hoy, aunque sea poco.",
  "La constancia vence al talento.",
  "Hazlo incluso sin ganas.",
  "Un paso pequeño también cuenta.",
  "Hoy construyes tu disciplina.",
  "Avanza aunque sea despacio.",
  "Tu esfuerzo diario vale.",
  "Sigue aunque nadie mire.",
  "Lo difícil también forma carácter.",
  "No pares cuando cueste.",
  "La repetición crea progreso real.",
  "Tu compromiso importa hoy.",
  "Mantén el rumbo siempre.",
  "Hazlo incluso con duda.",
  "Hoy suma otro intento.",
  "Tu constancia te cambia.",
  "Da un paso más.",
  "El progreso es acumulativo.",
  "No abandones por cansancio.",
  "Cada día cuenta.",
  "Hazlo aunque sea mínimo.",
  "El esfuerzo constante gana.",
  "Mantén tu palabra contigo.",
  "La disciplina se entrena.",
  "Hoy repite tu hábito.",
  "No busques excusas fáciles.",
  "Avanza aunque cueste hoy.",
  "Un día más de constancia.",
  "La práctica fortalece tu mente.",
  "Cumple lo que prometiste.",
  "Repite hasta que mejore.",
  "Hazlo incluso aburrido.",
  "Tu futuro se construye hoy.",
  "Persevera aunque sea lento.",
  "Otro día de disciplina.",
  "No dependas de motivación.",
  "La constancia cambia resultados.",
  "Hoy entrena tu carácter.",
  "Sigue aunque parezca pequeño.",
  "Tu hábito está creciendo.",
  "No rompas tu racha.",
  "Hazlo incluso cansado.",
  "Un intento más hoy.",
  "El esfuerzo diario transforma.",
  "Tu progreso se acumula.",
  "No te detengas hoy.",
  "Cumple tu compromiso diario.",
  "Avanza incluso con dudas.",
  "Mantén tu meta presente.",
  "La práctica crea habilidad.",
  "Tu disciplina te guía.",
  "Hoy también cuenta.",
  "Sigue incluso lento.",
  "Tu esfuerzo suma siempre.",
  "Hazlo sin buscar perfección.",
  "La constancia forma resultados.",
  "Da otro pequeño paso.",
  "No abandones el proceso.",
  "Hoy construyes resistencia mental.",
  "Cumple otra vez.",
  "Tu progreso necesita repetición.",
  "Hazlo incluso sin motivación.",
  "Sigue aunque sea corto.",
  "Hoy refuerza tu hábito.",
  "Tu carácter crece así.",
  "Repite aunque sea simple.",
  "La perseverancia vale mucho.",
  "No te rindas temprano.",
  "Otro día de avance.",
  "Cumple lo planeado.",
  "Hazlo antes de dudar.",
  "Tu disciplina te fortalece.",
  "Sigue el plan diario.",
  "La práctica te mejora.",
  "Mantén tu esfuerzo constante.",
  "Hoy suma experiencia.",
  "No pares por flojera.",
  "Repite el proceso hoy.",
  "Tu constancia se nota.",
  "Avanza sin excusas.",
  "Un día más firme.",
  "Cumple aunque sea breve.",
  "La rutina crea progreso.",
  "Tu hábito se refuerza.",
  "Hazlo incluso incómodo.",
  "Persevera hoy otra vez.",
  "La disciplina es práctica.",
  "No pierdas tu enfoque.",
  "Hoy cuenta mucho.",
  "Sigue trabajando en silencio.",
  "Un intento más hoy.",
  "La repetición crea dominio.",
  "Cumple tu meta diaria.",
  "Hazlo incluso con cansancio.",
  "Tu constancia te define.",
  "No pares ahora.",
  "Da otro paso.",
  "Hoy fortaleces tu mente.",
  "Persevera con paciencia.",
  "Mantén tu hábito vivo.",
  "Hoy vuelve a intentarlo.",
  "Tu disciplina sigue creciendo.",
  "Cumple otra pequeña meta.",
  "La práctica constante enseña.",
  "Hazlo aunque sea corto.",
  "No rompas el ritmo.",
  "Tu avance se acumula.",
  "Sigue trabajando tranquilo.",
  "Hoy entrena tu mente.",
  "Da continuidad a tu hábito.",
  "Tu esfuerzo importa hoy.",
  "Repite incluso sin ganas.",
  "Avanza paso a paso.",
  "Hoy cuenta más de lo que crees.",
  "No abandones el proceso.",
  "Mantén tu compromiso firme.",
  "Otro día de práctica.",
  "Cumple incluso con dudas.",
  "La constancia se entrena.",
  "Hazlo aunque sea simple.",
  "Hoy suma experiencia nueva.",
  "Tu disciplina se fortalece.",
  "Sigue incluso con cansancio.",
  "La perseverancia crea resultados.",
  "Un paso más hoy.",
  "No pierdas tu racha.",
  "Repite con intención.",
  "Hoy también importa.",
  "Tu esfuerzo construye futuro.",
  "Avanza sin detenerte.",
  "Cumple otro pequeño reto.",
  "La práctica te mejora.",
  "Mantén tu meta clara.",
  "Hazlo incluso aburrido.",
  "Tu constancia vale mucho.",
  "Sigue sumando días.",
  "Hoy forma tu carácter.",
  "No pares ahora.",
  "Repite una vez más.",
  "Tu hábito sigue creciendo.",
  "Hoy avanza un poco.",
  "La disciplina se construye.",
  "Cumple contigo mismo.",
  "No abandones temprano.",
  "Tu progreso es real.",
  "Repite el proceso.",
  "Hoy cuenta otra vez.",
  "Sigue aunque cueste.",
  "Un día más firme.",
  "Tu compromiso continúa.",
  "Hazlo incluso cansado.",
  "La constancia cambia todo.",
  "Da otro pequeño paso.",
  "Hoy también suma.",
  "Tu esfuerzo vale.",
  "Mantén tu rutina.",
  "No te detengas hoy.",
  "Repite con paciencia.",
  "Tu progreso avanza.",
  "Cumple otra vez.",
  "Hoy fortalece tu disciplina.",
  "Sigue incluso lento.",
  "La repetición enseña.",
  "No abandones ahora.",
  "Tu hábito se forma.",
  "Repite tu esfuerzo.",
  "Hoy mantén constancia.",
  "Tu progreso sigue.",
  "Cumple otro intento.",
  "Avanza con calma.",
  "Hoy suma otro paso.",
  "La perseverancia funciona.",
  "Mantén tu enfoque.",
  "Tu disciplina crece.",
  "No rompas el ritmo.",
  "Repite con intención.",
  "Hoy también cuenta.",
  "Sigue trabajando firme.",
  "Cumple tu meta.",
  "Tu constancia importa.",
  "Hazlo incluso corto.",
  "La práctica mejora todo.",
  "Otro día de avance.",
  "Mantén tu compromiso.",
  "Hoy fortalece tu hábito.",
  "Tu disciplina avanza.",
  "Repite otra vez.",
  "No abandones hoy.",
  "Sigue incluso cansado.",
  "Tu progreso continúa.",
  "Hoy da otro paso.",
  "Tu constancia suma.",
  "La repetición fortalece.",
  "Mantén tu rumbo.",
  "Cumple tu esfuerzo.",
  "No pares hoy.",
  "Sigue adelante.",
  "Hoy cuenta otra vez.",
  "Tu hábito crece.",
  "Avanza con disciplina.",
  "Hoy vuelve a cumplir.",
  "Mantén tu disciplina diaria.",
  "Tu esfuerzo sigue contando.",
  "No rompas tu constancia.",
  "Repite el hábito hoy.",
  "Un pequeño avance basta.",
  "Sigue incluso sin ganas.",
  "La práctica te fortalece.",
  "Hoy suma experiencia.",
  "Tu progreso continúa.",
  "Cumple otro intento hoy.",
  "Mantén tu compromiso firme.",
  "Repite aunque sea corto.",
  "Tu constancia vale mucho.",
  "Sigue un día más.",
  "Hoy fortalece tu mente.",
  "No abandones temprano.",
  "Tu disciplina crece.",
  "Hazlo incluso cansado.",
  "Avanza paso a paso.",
  "Hoy entrena tu carácter.",
  "Repite con paciencia.",
  "Tu hábito sigue creciendo.",
  "Mantén tu rumbo claro.",
  "Un esfuerzo más hoy.",
  "No pierdas el ritmo.",
  "Tu progreso se acumula.",
  "Sigue trabajando firme.",
  "Hoy cuenta de nuevo.",
  "Cumple contigo mismo.",
  "La constancia crea cambio.",
  "Da otro pequeño paso.",
  "Hoy suma disciplina.",
  "No te detengas ahora.",
  "Tu hábito se refuerza.",
  "Repite con intención.",
  "Hoy también importa.",
  "Mantén tu esfuerzo.",
  "Tu progreso sigue vivo.",
  "Cumple otra vez hoy.",
  "Sigue incluso despacio.",
  "La práctica crea dominio.",
  "Hoy fortalece tu hábito.",
  "No rompas tu racha.",
  "Tu disciplina se forma.",
  "Hazlo aunque sea simple.",
  "Repite tu esfuerzo diario.",
  "Hoy avanza un poco.",
  "Tu constancia suma.",
  "Sigue adelante siempre.",
  "Hoy cumple tu meta.",
  "Mantén tu compromiso.",
  "Repite con calma.",
  "Tu progreso continúa.",
  "No abandones hoy.",
  "Sigue un paso más.",
  "Hoy refuerza tu disciplina.",
  "Tu hábito se consolida.",
  "Hazlo incluso aburrido.",
  "Avanza sin excusas.",
  "Hoy vuelve a intentarlo.",
  "La perseverancia funciona.",
  "Tu esfuerzo vale.",
  "No rompas la rutina.",
  "Mantén tu enfoque.",
  "Repite el proceso.",
  "Hoy cuenta otra vez.",
  "Tu disciplina avanza.",
  "Sigue sumando días.",
  "Cumple otro intento.",
  "Hoy fortalece tu mente.",
  "Mantén tu hábito.",
  "Tu constancia se nota.",
  "Repite con constancia.",
  "No abandones el proceso.",
  "Tu progreso es real.",
  "Sigue trabajando firme.",
  "Hoy suma experiencia.",
  "Cumple tu palabra.",
  "Avanza otro paso.",
  "Hoy también suma.",
  "La repetición mejora.",
  "Mantén tu esfuerzo.",
  "Tu hábito crece.",
  "No te detengas hoy.",
  "Repite una vez más.",
  "Tu disciplina continúa.",
  "Hoy cuenta mucho.",
  "Sigue incluso cansado.",
  "Cumple otra vez.",
  "Hoy entrena tu constancia.",
  "Mantén tu rumbo.",
  "Tu progreso sigue.",
  "Repite con paciencia.",
  "No rompas tu hábito.",
  "Tu esfuerzo construye.",
  "Sigue avanzando hoy.",
  "Hoy fortalece tu carácter.",
  "Cumple un paso más.",
  "Tu disciplina permanece.",
  "Hoy repite tu hábito.",
  "Mantén tu constancia.",
  "Tu progreso avanza.",
  "No abandones ahora.",
  "Repite con calma.",
  "Tu disciplina suma.",
  "Sigue un día más.",
  "Hoy también importa.",
  "Cumple otro intento.",
  "Avanza con paciencia.",
  "Hoy fortalece tu rutina.",
  "Mantén tu compromiso.",
  "Tu hábito se forma.",
  "Repite con disciplina.",
  "No rompas el ritmo.",
  "Tu constancia funciona.",
  "Sigue trabajando firme.",
  "Hoy suma progreso.",
  "Cumple tu meta diaria.",
  "Avanza paso a paso.",
  "Hoy mantén constancia.",
  "Tu progreso continúa.",
  "Repite incluso corto.",
  "No abandones hoy.",
  "Tu disciplina crece.",
  "Sigue intentando siempre.",
  "Hoy fortalece tu hábito.",
  "Tu constancia cuenta.",
  "Cumple otro paso.",
  "Avanza con enfoque.",
  "Hoy repite otra vez.",
  "Mantén tu disciplina.",
  "Tu hábito mejora.",
  "No rompas tu racha.",
  "Sigue un día más.",
  "Hoy cuenta nuevamente.",
  "Repite con paciencia.",
  "Tu progreso sigue vivo.",
  "Cumple tu esfuerzo.",
  "Avanza con calma.",
  "Hoy entrena tu mente.",
  "Mantén tu hábito firme.",
  "Tu disciplina avanza.",
  "Repite aunque cansado.",
  "No abandones temprano.",
  "Tu constancia construye.",
  "Sigue sumando días.",
  "Hoy fortalece tu progreso.",
  "Cumple otra vez.",
  "Avanza sin parar.",
  "Hoy repite el hábito.",
  "Mantén tu compromiso.",
  "Tu progreso cuenta.",
  "No rompas el proceso.",
  "Sigue con disciplina.",
  "Hoy suma otro paso.",
  "Repite con intención.",
  "Tu constancia permanece.",
  "Cumple tu meta.",
  "Avanza con esfuerzo.",
  "Hoy entrena tu constancia.",
  "Mantén tu enfoque.",
  "Tu hábito sigue.",
  "Repite con paciencia.",
  "No abandones hoy.",
  "Tu disciplina importa.",
  "Sigue otro día.",
  "Hoy también suma.",
  "Cumple tu intento.",
  "Avanza sin pausa.",
  "Hoy mantén tu hábito.",
  "Tu progreso avanza.",
  "Repite con calma.",
  "No rompas tu racha.",
  "Tu disciplina crece.",
  "Sigue intentando.",
  "Hoy suma experiencia.",
  "Cumple otra vez.",
  "Tu constancia vale.",
  "Avanza con firmeza.",
  "Hoy fortalece tu rutina.",
  "Mantén tu esfuerzo.",
  "Tu progreso continúa.",
  "Repite con disciplina.",
  "No abandones ahora.",
  "Tu hábito mejora.",
  "Sigue avanzando.",
  "Hoy cuenta mucho.",
  "Cumple otro paso.",
  "Avanza con paciencia.",
  "Hoy repite el proceso.",
  "Mantén tu constancia.",
  "Tu disciplina funciona.",
  "No rompas tu hábito.",
  "Sigue firme hoy.",
  "Hoy suma progreso.",
  "Repite con calma.",
  "Tu esfuerzo vale.",
  "Cumple tu meta.",
  "Avanza paso firme.",
  "Hoy fortalece tu mente.",
  "Mantén tu hábito vivo.",
  "Tu progreso sigue.",
  "Repite tu disciplina.",
  "No abandones hoy.",
  "Tu constancia cuenta.",
  "Sigue otro día.",
  "Hoy suma esfuerzo.",
  "Cumple nuevamente.",
  "Avanza con intención.",
  "Hoy entrena tu carácter.",
  "Mantén tu progreso.",
  "Tu hábito crece.",
  "Repite con constancia.",
  "No rompas tu ritmo.",
  "Tu disciplina avanza.",
  "Sigue trabajando.",
  "Hoy también cuenta.",
  "Cumple otro intento.",
  "Avanza con calma.",
  "Hoy repite tu hábito.",
  "Mantén tu compromiso.",
  "Tu progreso continúa.",
  "Repite con paciencia.",
  "No abandones el proceso.",
  "Tu disciplina vale.",
  "Sigue sumando días.",
  "Hoy fortalece tu mente.",
  "Cumple otra vez.",
  "Avanza firme hoy.",
  "Hoy entrena tu constancia.",
  "Mantén tu hábito.",
  "Tu progreso avanza.",
  "Repite con calma.",
  "No rompas la racha.",
  "Tu disciplina crece.",
  "Sigue adelante.",
  "Hoy suma experiencia.",
  "Cumple tu meta.",
  "Avanza con enfoque.",
  "Hoy repite el esfuerzo.",
  "Mantén tu constancia.",
  "Tu hábito continúa.",
  "Repite con disciplina.",
  "No abandones ahora.",
  "Tu progreso importa.",
  "Sigue otro día más.",
  "Hoy fortalece tu hábito.",
  "Cumple otra vez.",
  "Avanza sin pausa.",
  "Hoy suma otro intento.",
  "Mantén tu compromiso firme.",
  "Tu disciplina avanza.",
  "Repite con paciencia.",
  "No rompas tu proceso.",
  "Tu progreso continúa.",
  "Sigue intentando hoy.",
  "Hoy también cuenta.",
  "Cumple otro paso.",
  "Avanza con calma.",
  "Hoy fortalece tu rutina.",
  "Mantén tu hábito diario.",
  "Tu progreso sigue.",
  "Repite con constancia.",
  "No abandones hoy.",
  "Tu disciplina suma.",
  "Sigue trabajando.",
  "Hoy cuenta otra vez.",
  "Cumple tu meta diaria.",
  "Avanza paso firme.",
  "Hoy repite el proceso.",
  "Mantén tu constancia.",
  "Tu hábito crece.",
  "Repite con paciencia.",
  "No rompas la racha.",
  "Tu disciplina continúa.",
  "Sigue adelante hoy.",
  "Hoy suma experiencia.",
  "Cumple nuevamente.",
  "Avanza con enfoque.",
  "Hoy entrena tu mente.",
  "Mantén tu hábito firme.",
  "Tu progreso avanza.",
  "Repite con calma.",
  "No abandones el hábito.",
  "Tu disciplina importa.",
  "Sigue un día más.",
  "Hoy también suma.",
  "Cumple tu esfuerzo.",
  "Avanza con paciencia.",
  "Hoy repite otra vez.",
  "Mantén tu compromiso.",
  "Tu progreso continúa.",
  "Repite con disciplina.",
  "No rompas tu ritmo.",
  "Tu constancia funciona.",
  "Sigue trabajando firme.",
  "Hoy fortalece tu carácter.",
  "Cumple un paso más.",
  "Tu constancia te transformó.",
];
